### ISSUE TITLE
when i compile lib so after this error occur 

### ISSUE THREAD

**Issue by yashshekhada** [webianks/ScrollChoice#3]
![2017-06-22](https://user-images.githubusercontent.com/28475432/27427437-98e9744e-575c-11e7-86e9-6411d9ccde11.png)
Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.

**Comment by webianks** [comment]
Okay !! I will check when I get time.

**Comment by yashshekhada** [comment]
compileSdkVersion 23
    buildToolsVersion "25.0.3"
    defaultConfig {
     
        minSdkVersion 16
        targetSdkVersion 23
}

on this gradle file ifi use <25 ro 24

**Comment by webianks** [comment]
Yes this is coming because library is compiled with sdk 25 and it has v-24 and v-25 resources. So they will not be resolved if you use sdk lower than 25. You can try to update the sdk to 25 if you don't have any problem.
